export function createAppState() {
  return {
    documents: {
      oldDoc: null,
      newDoc: null,
      pages: 0,
      currentPage: 0,
      oldSequence: null,
      newSequence: null,
      alignmentOps: [],
      generation: 0,
    },
    comparison: {
      dpi: 300,
      threshold: 128,
      tolerancePx: 0,
      dx: 0,
      dy: 0,
      manualAngle: 0,
      manualScale: 1,
      autoAlign: false,
      quadrantManual: new Map(),
    },
    visual: {
      mode: "diff",
      toggleSide: "old",
      toggleCache: null,
      pageCache: new Map(),
      alignmentCache: new Map(),
      quadrantCache: new Map(),
      renderGeneration: 0,
      quadrantGeneration: 0,
      rendered: false,
      currentPlan: null,
      splitCache: null,
      splitView: { scale: 1, tx: 0, ty: 0 },
      splitNeedsFit: true,
    },
    boxEditor: {
      showBoxes: true,
      currentBoxes: null,
      autoByPage: new Map(),
      editsByPage: new Map(),
      undoByPage: new Map(),
      revisionByPage: new Map(),
      editMode: false,
      selectedIndex: -1,
      drag: null,
    },
    textReview: {
      scale: null,
      extraction: null,
      highlights: null,
      page: 0,
      view: { scale: 1, tx: 0, ty: 0 },
      extractGeneration: 0,
      renderGeneration: 0,
      debugXYCut: false,
    },
    ui: { topMode: "visual", busy: null },
  };
}
